[tool.black]
line-length = 100
target-version = ['py311']
exclude = '''
  \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
'''

[tool.flake8]
max-line-length = 100